# Errors related to code
NO_ADAPTERS_FOUND = "No adapters found"
NO_DEVICE_FOUND = "No device found"
ERROR_CONNECTING = "Error: "
PROFILE_NOT_FOUND = "Profil non trouvé"
MISSING_BLUETOOTH_CONFIG = "Configuration BLUETOOTH manquante dans modes.config"

# Errors related to Bluetooth device interactions
DEVICE_NOT_FOUND = "Périphérique {address} non trouvé"
CONNECTION_ERROR = "Erreur de connexion : {error}"
DISCONNECTION_ERROR = "Erreur lors de la déconnexion : {error}"
RECONNECT_ERROR = "Impossible de se reconnecter"
WRITE_ERROR = "Erreur d'écriture : {error}"
STATE_READ_ERROR = "Erreur de lecture de l'état : {error}"
INVALID_BRIGHTNESS = "Luminosité invalide : {brightness}"
INVALID_RGB_COLOR = "Couleur RGB invalide"
STATE_RETRIEVAL_ERROR = "Erreur lors de la récupération de l'état"
SUCCESS_CONNECTION = "Lampe connectée avec succès!"
FAILED_CONNECTION = "Échec de la connexion"
LAMP_NOT_CONNECTED = "Lampe non connectée"
TURN_OFF_LOG = "Extinction du périphérique"
TURN_ON_LOG = "Allumage du périphérique"
SET_COLOR_LOG = "Définition de la couleur RGB({r},{g},{b})"
SET_BRIGHTNESS_LOG = "Réglage luminosité à {brightness}%"